"""
Reporter — Azure DevOps PR comments & Azure Table Storage logging.

Functions:
  - post_pr_comment:      Posts a formatted markdown comment on the PR.
  - log_to_table_storage: Writes each violation as a row in Table Storage.
  - format_markdown:      Builds the markdown PR comment body.
"""

import os
import json
import datetime
import uuid
from typing import Any

import requests

from policy_engine.models import PolicyResult, Violation


# ═══════════════════════════════════════════════════════════════════════════
# Markdown Formatting
# ═══════════════════════════════════════════════════════════════════════════

def format_markdown(result: PolicyResult) -> str:
    """
    Build a markdown-formatted PR comment body from a PolicyResult.
    """
    lines: list[str] = []

    if result.has_high_severity:
        lines.append("## ❌ Policy Gate — FAILED\n")
    else:
        lines.append("## ✅ Policy Gate — PASSED\n")

    lines.append(f"**{result.summary}**\n")

    if not result.violations:
        lines.append("No policy violations detected. Good job! 🎉\n")
        return "\n".join(lines)

    # Violations table
    lines.append("| # | Severity | Rule | Resource | Message |")
    lines.append("|---|----------|------|----------|---------|")

    for idx, v in enumerate(result.violations, 1):
        sev_icon = {
            "HIGH": "🔴 HIGH",
            "MEDIUM": "🟡 MEDIUM",
            "LOW": "🟢 LOW",
        }.get(v.severity.value, v.severity.value)

        # Truncate long messages for the table
        msg = v.message[:120] + "…" if len(v.message) > 120 else v.message
        lines.append(
            f"| {idx} | {sev_icon} | `{v.rule_id}` | `{v.resource_address}` | {msg} |"
        )

    lines.append("")

    if result.has_high_severity:
        lines.append(
            "> ⛔ **This PR is blocked.** Fix all HIGH-severity violations before merging.\n"
        )

    lines.append(
        "<sub>Generated by <b>azure-policy-gate</b> — "
        f"{datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%d %H:%M:%S')} UTC</sub>\n"
    )

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Azure DevOps PR Comment
# ═══════════════════════════════════════════════════════════════════════════

def post_pr_comment(result: PolicyResult) -> bool:
    """
    Post a markdown comment on the current Azure DevOps pull request.

    Reads the following environment variables (set automatically by
    Azure Pipelines or manually for local testing):

        SYSTEM_TEAMFOUNDATIONCOLLECTIONURI  — org URL
        SYSTEM_TEAMPROJECT                  — project name
        BUILD_REPOSITORY_ID                 — repo ID
        SYSTEM_PULLREQUEST_PULLREQUESTID    — PR number
        SYSTEM_ACCESSTOKEN                  — OAuth token

    Returns True on success, False otherwise.
    """
    org_url = os.environ.get("SYSTEM_TEAMFOUNDATIONCOLLECTIONURI", "").rstrip("/")
    project = os.environ.get("SYSTEM_TEAMPROJECT", "")
    repo_id = os.environ.get("BUILD_REPOSITORY_ID", "")
    pr_id = os.environ.get("SYSTEM_PULLREQUEST_PULLREQUESTID", "")
    token = os.environ.get("SYSTEM_ACCESSTOKEN", "")

    if not all([org_url, project, repo_id, pr_id, token]):
        print(
            "[reporter] ⚠  Missing Azure DevOps environment variables — "
            "skipping PR comment."
        )
        return False

    url = (
        f"{org_url}/{project}/_apis/git/repositories/{repo_id}"
        f"/pullRequests/{pr_id}/threads?api-version=7.1"
    )

    body = format_markdown(result)

    payload = {
        "comments": [
            {
                "parentCommentId": 0,
                "content": body,
                "commentType": 1,   # 1 = text
            }
        ],
        "status": 1,  # 1 = active
    }

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {token}",
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        print(f"[reporter] ✅ PR comment posted successfully (thread ID: "
              f"{resp.json().get('id', '?')})")
        return True
    except requests.RequestException as exc:
        print(f"[reporter] ❌ Failed to post PR comment: {exc}")
        return False


# ═══════════════════════════════════════════════════════════════════════════
# Azure Table Storage Logging
# ═══════════════════════════════════════════════════════════════════════════

def log_to_table_storage(
    result: PolicyResult,
    pr_number: str = "",
    repository: str = "",
) -> bool:
    """
    Write each violation (and a summary row) to Azure Table Storage.

    Environment variables:
        AZURE_STORAGE_CONNECTION_STRING  — connection string for the Storage Account
        VIOLATIONS_TABLE_NAME            — table name (default: PolicyViolations)

    Returns True on success.
    """
    conn_str = os.environ.get("AZURE_STORAGE_CONNECTION_STRING", "")
    table_name = os.environ.get("VIOLATIONS_TABLE_NAME", "PolicyViolations")

    if not conn_str:
        print(
            "[reporter] ⚠  AZURE_STORAGE_CONNECTION_STRING not set — "
            "skipping Table Storage logging."
        )
        return False

    try:
        from azure.data.tables import TableClient
    except ImportError:
        print("[reporter] ❌ azure-data-tables package not installed.")
        return False

    timestamp = datetime.datetime.utcnow().isoformat() + "Z"
    outcome = "FAIL" if result.has_high_severity else "PASS"
    run_id = str(uuid.uuid4())[:8]

    try:
        client = TableClient.from_connection_string(conn_str, table_name)

        # Write one entity per violation
        for idx, v in enumerate(result.violations):
            entity = {
                "PartitionKey": pr_number or "local",
                "RowKey": f"{run_id}-{idx:04d}",
                "Timestamp_UTC": timestamp,
                "PRNumber": pr_number,
                "Repository": repository,
                "Outcome": outcome,
                "RuleId": v.rule_id,
                "ResourceAddress": v.resource_address,
                "ResourceType": v.resource_type,
                "Severity": v.severity.value,
                "Message": v.message,
                "Details": json.dumps(v.details),
            }
            client.upsert_entity(entity)

        # Summary row
        summary_entity = {
            "PartitionKey": pr_number or "local",
            "RowKey": f"{run_id}-summary",
            "Timestamp_UTC": timestamp,
            "PRNumber": pr_number,
            "Repository": repository,
            "Outcome": outcome,
            "RuleId": "SUMMARY",
            "ResourceAddress": "",
            "ResourceType": "",
            "Severity": "",
            "Message": result.summary,
            "Details": "",
        }
        client.upsert_entity(summary_entity)

        print(
            f"[reporter] ✅ Logged {len(result.violations)} violation(s) + summary "
            f"to table '{table_name}' (outcome: {outcome})"
        )
        return True

    except Exception as exc:
        print(f"[reporter] ❌ Table Storage write failed: {exc}")
        return False
